package app

const indexHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>s-watcher</title><style>
:root{color-scheme:dark;--bg:#0b0d10;--card:#151920;--ink:#f4f1ea;--muted:#9da5b2;--gold:#f2a900;--line:#29303a;--bad:#ff746c;--good:#72d69b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,sans-serif}.wrap{width:min(1120px,94vw);margin:48px auto}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.controls{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.controls button{background:transparent;color:var(--muted);border-color:var(--line)}h1{font-size:2.4rem;margin:0}.tag{color:var(--gold);letter-spacing:.08em;text-transform:uppercase;font-size:.78rem}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:22px;margin-top:22px}.identity{display:flex;gap:16px;align-items:center}.identity img{width:84px;height:84px;border-radius:14px;background:#0e1116;border:1px solid var(--line)}form.add{display:grid;grid-template-columns:1fr 1fr 2fr 150px auto;gap:10px}.options{grid-column:1/-1;display:flex;gap:20px;align-items:center;color:var(--muted);font-size:.85rem}.options label{display:flex;gap:7px;align-items:center}.options input{width:76px}.options input[type=checkbox]{width:auto}input,select,button{border:1px solid var(--line);border-radius:8px;padding:11px 13px;background:#0e1116;color:var(--ink)}button{background:var(--gold);border-color:var(--gold);color:#17120a;font-weight:700;cursor:pointer}.delete button,.edit button{background:transparent;color:var(--muted);border-color:var(--line)}.edit{display:grid;grid-template-columns:1fr 1fr auto;gap:6px;margin-top:10px}.edit input,.edit button{padding:7px 9px;min-width:0}.category{display:inline-block;padding:2px 8px;border:1px solid #5e4b18;border-radius:999px;color:var(--gold);font-size:.72rem;margin-bottom:5px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px 8px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:.75rem;text-transform:uppercase}.address,.tx{font-family:ui-monospace,monospace;font-size:.78rem;word-break:break-all;color:var(--muted)}.masked{font-family:"Noto Sans Symbols 2","Segoe UI Symbol",ui-monospace,monospace;letter-spacing:.12em}.error,.sent{color:var(--bad)}.received{color:var(--good)}.kind{text-transform:capitalize}.empty{color:var(--muted);padding:20px 0}dialog{width:min(480px,90vw);border:1px solid var(--line);border-radius:14px;padding:24px;background:var(--card);color:var(--ink);box-shadow:0 24px 80px #000b}dialog::backdrop{background:#000a}dialog h2{margin-top:0}dialog p{color:var(--muted)}dialog form{display:flex;justify-content:flex-end;margin-top:22px}@media(max-width:700px){.top{display:block}.controls{justify-content:flex-start;margin-top:16px}form.add,.edit{grid-template-columns:1fr}.options{align-items:flex-start;flex-direction:column;gap:8px}table,thead,tbody,tr,th,td{display:block}thead{display:none}tr{padding:12px 0;border-bottom:1px solid var(--line)}td{border:0;padding:4px 0}}
</style></head><body><main class="wrap"><header class="top"><div><div class="tag">Satoshi's watcher</div><h1>s-watcher</h1><p>Local, watch-only Bitcoin activity monitoring through your StartOS Electrs.</p></div><div class="controls"><form method="post" action="/privacy"><button>{{if .PrivacyMode}}Show balances and identifiers{{else}}Hide balances and identifiers{{end}}</button></form><form method="post" action="/logout"><button>Sign out</button></form></div></header>
{{if .Nostr}}<section class="card identity"><img src="{{.Nostr.Avatar}}" alt="Pixelbot avatar"><div><div class="tag">Nostr notification sender</div><h2>{{.Nostr.Name}}</h2><div class="address">{{.Nostr.Npub}}</div></div></section>{{end}}
<section class="card"><form class="add" method="post" action="/watches"><input name="label" maxlength="80" required placeholder="Name, e.g. Website BTC"><input name="category" maxlength="60" placeholder="Group, e.g. Donations"><input name="source" required autocomplete="off" placeholder="Bitcoin address, xpub/ypub/zpub, or descriptor"><select name="script_type" aria-label="Address type" hidden><option value="">Choose xpub address type</option><option value="native-segwit">Native SegWit</option><option value="nested-segwit">Nested SegWit</option><option value="legacy">Legacy</option><option value="taproot">Taproot</option></select><button>Add watch</button><div class="options" hidden><label>Derive <input name="count" type="number" min="1" max="500" value="20"> addresses per branch</label><label><input name="include_change" type="checkbox" checked> Include /1 change branch</label><span>Descriptors, ypubs, and zpubs determine their address type automatically.</span></div></form></section>
<section class="card"><h2>Watched wallets and addresses</h2>{{if .Groups}}<table><thead><tr><th>Name and group</th><th>Coverage</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{{range .Groups}}<tr><td><span class="category">{{.Category}}</span><br><strong>{{.Label}}</strong><div class="address">{{.DisplaySource}}</div><form class="edit" method="post" action="/groups/{{.ID}}/update"><input name="label" maxlength="80" required value="{{.Label}}" aria-label="Watch name"><input name="category" maxlength="60" required value="{{.Category}}" aria-label="Watch group"><button>Save</button></form></td><td>{{.Addresses}} addresses<div class="address">{{.ScriptType}}{{if .IncludeChange}} · receive + change{{end}}</div></td><td class="{{if $.PrivacyMode}}masked{{end}}">{{.DisplayBalance}}</td><td>{{if .LastError}}<span class="error">{{.LastError}}</span>{{else if eq .Ready .Addresses}}Checked {{.LastChecked.Format "2006-01-02 15:04 UTC"}}{{else}}{{.Ready}} / {{.Addresses}} initialized{{end}}</td><td><form class="delete" method="post" action="/groups/{{.ID}}/delete"><button>Remove</button></form></td></tr>{{end}}</tbody></table>{{else}}<div class="empty">No addresses, extended keys, or descriptors are being watched yet.</div>{{end}}</section>
<section class="card"><h2>New activity</h2>{{if .Events}}<table><thead><tr><th>Watch</th><th>Activity</th><th>Amount</th><th>Transaction</th><th>State</th><th>Detected</th></tr></thead><tbody>{{range .Events}}<tr><td>{{if .GroupID}}{{watchLabel .GroupID}}{{else}}{{watchLabel .WatchID}}{{end}}</td><td class="kind {{.Direction}}">{{.Direction}}</td><td class="{{if $.PrivacyMode}}masked{{end}}">{{.DisplayAmount}}</td><td class="tx">{{.DisplayTxID}}</td><td>{{if gt .Height 0}}Block {{.Height}}{{else}}Mempool{{end}}</td><td>{{.SeenAt.Format "2006-01-02 15:04 UTC"}}</td></tr>{{end}}</tbody></table>{{else}}<div class="empty">No new activity detected after the initial scans.</div>{{end}}</section>
</main><dialog id="watch-error"><h2>Could not add watch</h2><p></p><form method="dialog"><button>Close</button></form></dialog><script>
const addForm=document.querySelector('form.add'),source=addForm.elements.source,type=addForm.elements.script_type,options=addForm.querySelector('.options'),errorDialog=document.querySelector('#watch-error');
function updateSourceFields(){const value=source.value.trim(),plainXpub=value.startsWith('xpub')&&!value.includes('('),derivable=/^(xpub|ypub|zpub)/.test(value)||value.includes('(');type.hidden=!plainXpub;type.required=plainXpub;if(!plainXpub)type.value='';options.hidden=!derivable}
source.addEventListener('input',updateSourceFields);updateSourceFields();
addForm.addEventListener('submit',async event=>{event.preventDefault();const button=addForm.querySelector('button[type="submit"],button:not([type])');button.disabled=true;try{const response=await fetch(addForm.action,{method:'POST',headers:{Accept:'application/json'},body:new FormData(addForm)});if(response.ok){location.reload();return}const body=await response.json().catch(()=>({error:'The watch could not be added.'}));errorDialog.querySelector('p').textContent=body.error||'The watch could not be added.';errorDialog.showModal()}catch(_){errorDialog.querySelector('p').textContent='s-watcher could not process the request. Please try again.';errorDialog.showModal()}finally{button.disabled=false}});
</script></body></html>`

const loginHTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · s-watcher</title><style>:root{color-scheme:dark;--bg:#0b0d10;--card:#151920;--ink:#f4f1ea;--muted:#9da5b2;--gold:#f2a900;--line:#29303a;--bad:#ff746c}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,sans-serif}.login{width:min(420px,92vw);padding:28px;background:var(--card);border:1px solid var(--line);border-radius:16px}.tag{color:var(--gold);letter-spacing:.08em;text-transform:uppercase;font-size:.78rem}h1{margin:.2em 0}p{color:var(--muted)}form{display:grid;gap:12px;margin-top:24px}input,button{width:100%;border:1px solid var(--line);border-radius:8px;padding:12px 14px;background:#0e1116;color:var(--ink)}button{background:var(--gold);border-color:var(--gold);color:#17120a;font-weight:700;cursor:pointer}.error{color:var(--bad)}</style></head><body><main class="login"><div class="tag">Satoshi's watcher</div><h1>s-watcher</h1>{{if .Configured}}{{if .Error}}<p class="error">Incorrect password.</p>{{else}}<p>Enter your web password to continue.</p>{{end}}<form method="post" action="/login"><input name="password" type="password" minlength="12" maxlength="256" required autofocus autocomplete="current-password" placeholder="Web password"><button>Sign in</button></form>{{else}}<p>The Web Interface is locked. Open the s-watcher service actions in StartOS and run <strong>Set Web Password</strong> first.</p>{{end}}</main></body></html>`
